name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to the directory containing the Dockerfile (current directory in this case)
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.run_id }}
        env:
          DOCKER_USERNAME:  ${{ github.actor }}
          DOCKER_PASSWORD:  ${{ secrets.GITHUB_TOKEN }}